// GENERATED by scripts/gen-image-dims.mjs — do not edit by hand.
// Intrinsic pixel dimensions of every image in public/assets/img/lib.

export const IMG_DIMS: Record<string, [number, number]> = {
  "adams-peak": [850, 1024],
  "ancient-ruins": [1024, 683],
  "anuradhapura": [844, 1024],
  "beach-boats": [1125, 1500],
  "beach-sunset": [1400, 933],
  "buddha-statues": [669, 446],
  "cave-view": [819, 1024],
  "colombo-night": [768, 385],
  "colonial": [1024, 576],
  "cuisine-bowls": [1400, 1050],
  "cuisine": [1400, 1050],
  "ella-ninearch": [1024, 685],
  "galle-fort": [1125, 1500],
  "galle-light": [1000, 1500],
  "harbor-dusk": [1024, 683],
  "hill-lake": [1024, 683],
  "kandy-temple": [1024, 634],
  "leopard-road": [1400, 788],
  "leopard": [1000, 1500],
  "mirissa-bay": [1400, 1050],
  "nuwara-eliya": [1024, 643],
  "red-mosque": [592, 1024],
  "river-safari": [448, 336],
  "safari-jeep": [730, 400],
  "sigiriya": [1024, 683],
  "sunset-temple": [1000, 749],
  "surf-sunset": [1400, 935],
  "train-ella": [736, 920],
};

/** Intrinsic [width, height], for width/height attributes that prevent CLS. */
export const dims = (name: string): [number, number] => IMG_DIMS[name] ?? [1600, 1067];
